[project]
name = "reinforcementlearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[atari,mujoco]>=1.2.0",
    "torch>=2.8.0",
    "wandb>=0.21.1",
]
